### ISSUE TITLE
Unintended retention of '%%%%%' term after forced paragraph separation

### ISSUE THREAD

**Issue by ilpoli** [averkij/lingtrain-aligner#8]
I am using the "%%%%%." term to force separate lines into individual paragraphs. Here is an example:
```
Neil%%%%%h5.
We’ll discuss that more in a moment and find out if chatbots really think for themselves. But first I have a question for you, Rob. The first computer program that allowed some kind of plausible conversation between humans and machines was invented in 1966, but what was it called? Was it:

a) ALEXA %%%%%.

b) ELIZA %%%%%.

c) PARRY %%%%%.
```

While this process successfully separates the items into different paragraphs, it doesn't remove the "%%%%%" term, which is consequently retained in the final document.

<img width="687" alt="image" src="https://github.com/averkij/lingtrain-aligner/assets/4352611/83466bcb-a7cd-4bc5-8c12-37467764091c">

**Comment by averkij** [comment]
"%%%%%." marks adds only automatically on the lienbreaks. So you don't need to add them directly. Just add line breaks to your text and check that when you generating the book the appropriate side is selected ("from" or "to").
